--
-- Table structure for table `EVENT`
--

DROP TABLE IF EXISTS `EVENT`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `EVENT` (
  `E_ID` int(11) NOT NULL,
  `E_CREATOR` int(7) NOT NULL,
  `E_TITLE` char(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `E_LAT_DEG` int(2) NOT NULL,
  `E_LAT_MIN` int(2) NOT NULL,
  `E_LAT_SEC` int(2) NOT NULL,
  `E_LONG_DEG` int(2) NOT NULL,
  `E_LONG_MIN` int(2) NOT NULL,
  `E_LONG_SEC` tinyint(2) NOT NULL,
  `E_DATE` date NOT NULL,
  `E_TIME_START` time NOT NULL,
  `E_TIME_END` time DEFAULT NULL,
  `E_TYPE` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `E_DESC` longtext CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `E_PRIVATE` char(1) NOT NULL,
  `E_AGE_GROUP` varchar(20) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `E_PRICE` float(5,2) DEFAULT NULL,
  `E_FOOD` char(1) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `E_FOOD_TYPE` char(3) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `E_DRINK` char(1) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `E_DRINK_TYPE` char(3) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `E_BYO` char(1) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `E_ATTIRE` char(1) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `E_ATTIRE_TYPE` char(3) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `E_SPONSOR` char(1) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `E_SPONSOR_TITLE` char(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `USER_U_ID` int(7) NOT NULL,
  `LT_FOOD_F_FOOD_TYPE` char(3) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `LT_ATTIRE_ATT_ATTIRE_TYPE` char(3) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `LT_DRINK_D_DRINK_TYPE` char(3) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `LT_AGE_AGE_CODE` int(3) NOT NULL,
  PRIMARY KEY (`E_ID`),
  KEY `fk_EVENT_USER1_idx` (`USER_U_ID`),
  KEY `fk_EVENT_LT_FOOD1_idx` (`LT_FOOD_F_FOOD_TYPE`),
  KEY `fk_EVENT_LT_ATTIRE1_idx` (`LT_ATTIRE_ATT_ATTIRE_TYPE`),
  KEY `fk_EVENT_LT_DRINK1_idx` (`LT_DRINK_D_DRINK_TYPE`),
  KEY `fk_EVENT_LT_AGE1_idx` (`LT_AGE_AGE_CODE`),
  CONSTRAINT `fk_EVENT_LT_AGE1` FOREIGN KEY (`LT_AGE_AGE_CODE`) REFERENCES `LT_AGE` (`AGE_CODE`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_EVENT_LT_ATTIRE1` FOREIGN KEY (`LT_ATTIRE_ATT_ATTIRE_TYPE`) REFERENCES `LT_ATTIRE` (`ATT_ATTIRE_TYPE`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_EVENT_LT_DRINK1` FOREIGN KEY (`LT_DRINK_D_DRINK_TYPE`) REFERENCES `LT_DRINK` (`D_DRINK_TYPE`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_EVENT_LT_FOOD1` FOREIGN KEY (`LT_FOOD_F_FOOD_TYPE`) REFERENCES `LT_FOOD` (`F_FOOD_TYPE`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_EVENT_USER1` FOREIGN KEY (`USER_U_ID`) REFERENCES `USER` (`U_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;
