--
-- Table structure for table `FEEDBACK`
--

DROP TABLE IF EXISTS `FEEDBACK`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `FEEDBACK` (
  `FB_ID` int(11) NOT NULL,
  `FB_FROM_ID` int(7) NOT NULL,
  `FB_EVENT_ID` int(11) NOT NULL,
  `FB_MESS` longtext COLLATE utf8_bin NOT NULL,
  `USER_U_ID` int(7) NOT NULL,
  `EVENT_E_ID` int(11) NOT NULL,
  PRIMARY KEY (`FB_ID`),
  KEY `fk_FEEDBACK_USER1_idx` (`USER_U_ID`),
  KEY `fk_FEEDBACK_EVENT1_idx` (`EVENT_E_ID`),
  CONSTRAINT `fk_FEEDBACK_EVENT1` FOREIGN KEY (`EVENT_E_ID`) REFERENCES `EVENT` (`E_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_FEEDBACK_USER1` FOREIGN KEY (`USER_U_ID`) REFERENCES `USER` (`U_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
/*!40101 SET character_set_client = @saved_cs_client */;
