SELECT E_ID,
E_TITLE,
CONCAT (E_LAT_DEG, '.',E_LAT_MIN,'.',E_LAT_SEC) LATITUDE,
CONCAT (E_LONG_DEG, '.', E_LONG_MIN,'.',E_LONG_SEC) LONGITUDE,
E_DATE,
E_TIME_START,
E_TIME_END,
E_TYPE,
E_DESC,
E_PRIVATE,
E_AGE_GROUP,
E_PRICE,
E_FOOD,
E_FOOD_TYPE,
E_DRINK,
E_DRINK_TYPE,
E_BYO,
E_ATTIRE,
E_ATTIRE_TYPE,
E_SPONSOR,
E_SPONSOR_TITLE
FROM EVENT
WHERE E_PRIVATE NOT LIKE 'Y'
AND E_AGE_GROUP LIKE '10';