ALTER TABLE `event` CHANGE `E_TYPE` `E_TYPE` VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `event` CHANGE `E_AGE_GROUP` `E_AGE_GROUP` VARCHAR(20) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL;
ALTER TABLE `event` CHANGE `E_FOOD_TYPE` `E_FOOD_TYPE` CHAR(3) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL;
ALTER TABLE `event` CHANGE `E_DRINK_TYPE` `E_DRINK_TYPE` CHAR(3) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL;
ALTER TABLE `event` CHANGE `E_ATTIRE_TYPE` `E_ATTIRE_TYPE` CHAR(3) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL;
